let pdata = [{
  id: 1,
  name: 'Shirt',
  topProduct: true,
  price: '₹100',
  type :'clothing',
  image: require('../images/shirt.png'),
  imageName: 'shirt.png',
},
{
  id: 2,
  name: 'Pant',
  topProduct: true,
  price: '₹100',
  type :'clothing',
  image: require('../images/jeans.png'),
  imageName: 'jeans.png',
},
{
  id: 3,
  name: 'T-shirt',
  topProduct: true,
  price: '₹100',
  type :'clothing',
  image: require('../images/tshirt.jpeg'),
  imageName: 'tshirt.jpeg',
},
{
  id: 4,
  name: 'Glasses',
  topProduct: true,
  price: '₹100',
  type :'accessories',
  image: require('../images/glasses.png'),
  imageName: 'glasses.png',
},
{
  id: 5,
  name: 'Glasses',
  topProduct: true,
  price: '₹100',
  type :'accessories',
  image: require('../images/glasses.png'),
  imageName: 'glasses.png',
},
{
  id: 6,
  name: 'Glasses',
  topProduct: true,
  price: '₹100',
  type :'accessories',
  image: require('../images/glasses.png'),
  imageName: 'glasses.png',
},
{
  id: 7,
  name: 'Glasses',
  topProduct: true,
  price: '₹100',
  type :'accessories',
  image: require('../images/glasses.png'),
  imageName: 'glasses.png',
},
{
  id: 8,
  name: 'Glasses',
  topProduct: true,
  price: '₹100',
  type :'accessories',
  image: require('../images/glasses.png'),
  imageName: 'glasses.png',
},
{
  id: 9,
  name: 'Pant',
  topProduct: true,
  price: '₹100',
  type :'clothing',
  image: require('../images/jeans.png'),
  imageName: 'jeans.png',
},
{
  id: 10,
  name: 'T-shirt',
  topProduct: true,
  price: '₹100',
  type :'clothing',
  image: require('../images/tshirt.jpeg'),
  imageName: 'tshirt.jpeg',
},
{
  id: 11,
  name: 'Glasses',
  topProduct: true,
  price: '₹100',
  type :'accessories',
  image: require('../images/glasses.png'),
  imageName: 'glasses.png',
},
]

export default pdata;